<?php

namespace OAuth\Unit\UserData\Exception;

use OAuth\UserData\Exception\InvalidExtractorException;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-08 at 00:27:44.
 */
class InvalidExtractorExceptionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var InvalidExtractorException
     */
    protected $exception;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->exception = new InvalidExtractorException('someClass');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetExtractorClass()
    {
        $this->assertEquals('someClass', $this->exception->getExtractorClass());
    }

    public function testGetMessageWithCustomMessage()
    {
        $exception = new InvalidExtractorException('someClass', 'custom message');
        $this->assertEquals('custom message', $exception->getMessage());
    }
}
